# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fabiocognigni.github.io
# title: Let's Blog!
# subtitle: Free thoughts around Software Engineering.
author: Fabero
simple_search: https://www.google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: "fabiocognigni"
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: true

# --------------------------------------  
# Octopress gallery
# --------------------------------------
mini_magick:
#  gallery_1_thumbnail:
#    source: images/galleries/gallery_1
#    destination: images/galleries/gallery_1/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
#    guitar_medium:
#      source: images/galleries/guitar
#      destination: images/galleries/guitar/medium
#      commands:
#        - resize: "600x400"
  vaporizer_thumbnail:
    source: images/galleries/vaporizer
    destination: images/galleries/vaporizer/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
#  sterilizer_thumbnail:
#    source: images/galleries/sterilizer
#    destination: images/galleries/sterilizer/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
  play-yard_thumbnail:
    source: images/galleries/play-yard
    destination: images/galleries/play-yard/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  play-carpet-1_thumbnail:
    source: images/galleries/play-carpet-1
    destination: images/galleries/play-carpet-1/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
#  play-carpet-2_thumbnail:
#    source: images/galleries/play-carpet-2
#    destination: images/galleries/play-carpet-2/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"      
#  chest-drawers-white_thumbnail:
#    source: images/galleries/chest-drawers-white
#    destination: images/galleries/chest-drawers-white/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
#  chest-drawers-black_thumbnail:
#    source: images/galleries/chest-drawers-black
#    destination: images/galleries/chest-drawers-black/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"      
#  couch_thumbnail:
#    source: images/galleries/couch
#    destination: images/galleries/couch/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
#  tv_thumbnail:
#    source: images/galleries/tv
#    destination: images/galleries/tv/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0" 
#  bookcase_thumbnail:
#    source: images/galleries/bookcase
#    destination: images/galleries/bookcase/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
  bed_thumbnail:
    source: images/galleries/bed
    destination: images/galleries/bed/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  crib_thumbnail:
    source: images/galleries/crib
    destination: images/galleries/crib/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  table_thumbnail:
    source: images/galleries/table
    destination: images/galleries/table/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  high-chair_thumbnail:
    source: images/galleries/high-chair
    destination: images/galleries/high-chair/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
#  baby-desk_thumbnail:
#    source: images/galleries/baby-desk
#    destination: images/galleries/baby-desk/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
  night-table_thumbnail:
    source: images/galleries/night-table
    destination: images/galleries/night-table/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
#  chest-drawers-small_thumbnail:
#    source: images/galleries/chest-drawers-small
#    destination: images/galleries/chest-drawers-small/thumbs
#    commands:
#      - thumbnail: "140x140^"
#      - crop: "140x140-0x0"
  changing-pad_thumbnail:
    source: images/galleries/changing-pad
    destination: images/galleries/changing-pad/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  bouncer_thumbnail:
    source: images/galleries/bouncer
    destination: images/galleries/bouncer/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  stroller_thumbnail:
    source: images/galleries/stroller
    destination: images/galleries/stroller/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"
  blender_thumbnail:
    source: images/galleries/blender
    destination: images/galleries/blender/thumbs
    commands:
      - thumbnail: "140x140^"
      - crop: "140x140-0x0"            